name: deploy

on:
  push:
    branches: [ ogame ]

jobs:
  ssh:
    runs-on: ubuntu-latest
    environment: ogame

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KORURI_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.KORURI_PORT }} ${{ secrets.KORURI_HOST }} >> ~/.ssh/known_hosts

      - name: Fetch Config Files
        run: |
          scp -i ~/.ssh/id_rsa \
          -P ${{ secrets.KORURI_PORT }} \
          ${{ secrets.KORURI_USER }}@${{ secrets.KORURI_HOST }}:/home/ubuntu/misskey.ogamen.cc/config/* \
          ./.config/

      - name: Copy compose.yml
        run: |
          cp ./compose_example.yml ./compose.yml

      - name: Build
        run: |
          docker compose build

      - name: Export imgae as tar.gz
        run: |
          docker save misskey-web:latest | gzip > misskey.tar.gz

      - name: Send Image tar
        run: |
          scp -i ~/.ssh/id_rsa \
          -P ${{ secrets.KORURI_PORT }} \
          misskey.tar.gz \
          ${{ secrets.KORURI_USER }}@${{ secrets.KORURI_HOST }}:/home/ubuntu/misskey.ogamen.cc

      - name: Deploy on Server
        run: |
          ssh -i ~/.ssh/id_rsa \
            -p ${{ secrets.KORURI_PORT }} \
            -o StrictHostKeyChecking=no \
            ${{ secrets.KORURI_USER }}@${{ secrets.KORURI_HOST }} << 'EOF'
              cd /home/ubuntu/misskey.ogamen.cc

              gunzip -c misskey.tar.gz | docker load
              rm misskey.tar.gz

              docker compose down
              docker compose up -d --remove-orphans
            EOF
