name: deploy

on:
  push:
    branches: [ ogame ]

jobs:
  ssh:
    runs-on: ubuntu-latest
    environment: ogame

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        run: |
          pwd
          ls -la

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KORURI_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.KORURI_PORT }} ${{ secrets.KORURI_HOST }} >> ~/.ssh/known_hosts

      - name: Fetch Config Files
        run: |
          scp -i ~/.ssh/id_rsa \
          -p ${{ secrets.KORURI_PORT }} \
          ${{ secrets.KORURI_USER }}@${{ secrets.KORURI_HOST }}:/home/ubuntu/misskey.ogamen.cc/config/* \
          /home/runner/work/Ogame3334/misskey/.config/

      - name: test
        run: ls -la /home/runner/work/Ogame3334/misskey/.config/
